### ISSUE TITLE
Friends - display friends issue

### ISSUE THREAD

**Issue by eggwhat** [SaintAngeLs/distributed_minispace#196]
Somehow i get the same student added twice as my friend. This is reflected in a db as two friend objects with the same ids.

![image](https://github.com/SaintAngeLs/distributed_minispace/assets/110856762/3f451d28-aca9-4abe-8b54-03fd9b04abc1)

**Comment by SaintAngeLs** [comment]
Your issue is related to chaos running deployments on the branches with frined-serivce implemented in other way and storing it to database. The only solution is to drop your friends.
