### ISSUE TITLE
Issue with the identity service in Blazor application

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/distributed_minispace#210]
After Signing-In to the user that does not exists, the identity service defines the Internal Exception but this exception is not handled in Blazor application. Please, I request you to resolve this issue.

**Comment by an2508374** [comment]
I will provide solving of this issue in frontend_merge branch.

**Comment by SaintAngeLs** [comment]
> I will provide solving of this issue in frontend_merge branch.

Thank you, @an2508374, I am looking forward for update.

**Comment by an2508374** [comment]
I've fixed it, we will have such alert there:
![Screenshot from 2024-05-28 00-17-42](https://github.com/SaintAngeLs/distributed_minispace/assets/148250180/50e3003a-2184-49f0-a5b6-813745ad7359)

**Comment by SaintAngeLs** [comment]
@an2508374 thank you! Nice work!
