### ISSUE TITLE
Using LocalStorage to store session data

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/distributed_minispace#217]
Generally, I've observed that we can store there any objects, not only authentication data, in quite easy way.

Thanks to that, in reports, admin has saved searching criteria no matter where he goes, and after going to page of report target, he can return directly to manage report dialog.

We have some other places, for example searching events and friends, where using this mechanism can improve user experience, and I will be able to update it later.

**Comment by SaintAngeLs** [comment]
@an2508374  @SaintAngeLs @eggwhat  please, remember to operate it with a full potential efficiency.

**Comment by SaintAngeLs** [comment]
Closed  as currently inactive.
