### ISSUE TITLE
Conflicts when merging frontend_fixes into dev

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/distributed_minispace#228]
I've created new branch frontend_merge from dev and merged there your branch frontend_fixes. There were a few merge conflicts so I've resolved them. Therefore, after you finish your work, you can merge frontend_fixes into frontend_merge and then create a pull request without any conflicts.
Btw, nice work with event cards, it's a magnificent enhancement!

**Comment by eggwhat** [comment]
Sure thank you, but I still haven't finished yet so hopefully it doesn't result in more conflicts.

**Comment by eggwhat** [comment]
This issue was resolved in #230
