### ISSUE TITLE
Why I've got so many notifications?

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/distributed_minispace#233]
I've observed I have 8184 items in my notification panel. Each of them appeared today, only after signing up and showed interest in one event and creating the test one.

I'm not sure that this situation is intended.

![1](https://github.com/SaintAngeLs/distributed_minispace/assets/148250180/6e82e439-aeb3-4f7d-ab61-ba1e11c0fd3a)
![2](https://github.com/SaintAngeLs/distributed_minispace/assets/148250180/e988e642-55c9-49a9-9958-3fbd577cd16f)
![3](https://github.com/SaintAngeLs/distributed_minispace/assets/148250180/55f781e4-783a-479d-8b3d-9cf74eb0a30f)

**Comment by eggwhat** [comment]
I have the same problem.

**Comment by SaintAngeLs** [comment]
This issue is related to start serving all the unrouted events published in the queue in server rabbit. I will provide more competent implementation of the cleaner service after 17:00.

**Comment by SaintAngeLs** [comment]
The issue was related to creating multiple objects in Event:
I previously used the data from the created 'notification' object passing it to  NotificationCreated by it's values like 'notification.notificationId' , which created 2 NotificationCreated Events as the result.

```
  var notification = new Notification(
                notificationId: Guid.NewGuid(),
                userId: eventArgs.StudentId,
                message: notificationMessage,
                status: NotificationStatus.Unread,
                createdAt: DateTime.UtcNow,
                updatedAt: null,
                relatedEntityId: eventArgs.EventId,
                eventType: NotificationEventType.StudentCancelledInterestInEvent,
                details: detailsHtml
            );

             
            studentNotifications.AddNotification(notification);
            await _studentNotificationsRepository.UpdateAsync(studentNotifications);

            var notificationCreatedEvent = new NotificationCreated(
                notificationId:  Guid.NewGuid(),
                userId: eventArgs.StudentId,
                message: notificationMessage,
                createdAt: DateTime.UtcNow,
                eventType: NotificationEventType.StudentCancelledInterestInEvent.ToString(),
                relatedEntityId: eventArgs.Even

```
