### ISSUE TITLE
Harmful git habits

### ISSUE THREAD

**Issue by eggwhat** [SaintAngeLs/distributed_minispace#240]
I just found out that one commit reverted all my changes to posts on dev 🙂🔫. Please be careful with your changes and your branches tracking. 

https://github.com/SaintAngeLs/distributed_minispace/commit/4b8ca3c38d1932b8f6098cb4fb9f99b9aed2f5c8

**Comment by SaintAngeLs** [comment]
@eggwhat, thank you, the problem is found. Will that be an issue to return inseparable changes?

**Comment by eggwhat** [comment]
It should be working fine now, but the tests are not compatible with the changes
