### ISSUE TITLE
Problem with inviting friends to an event

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/distributed_minispace#259]
After going to any event and trying to invite someone I've got such results:
![image](https://github.com/SaintAngeLs/distributed_minispace/assets/148250180/edf438c6-c7ae-434b-9534-ac4c68ec1771)
![image](https://github.com/SaintAngeLs/distributed_minispace/assets/148250180/ed43265d-d757-44de-bfd9-241004de90d8)

**Comment by an2508374** [comment]
Probably it is associated with account which existed in the past and now are deleted. After last commit in "frontend_updates" I have:

![image](https://github.com/SaintAngeLs/distributed_minispace/assets/148250180/b3f6fbcd-0cc1-457a-9fef-5f6cef842377)

**Comment by SaintAngeLs** [comment]
I've checked it up locally, and it is supposed to work.

**Comment by SaintAngeLs** [comment]
Server resources are unavailable now as I turned up prometheus. I would like to check it there.

**Comment by an2508374** [comment]
So I can fix it to not show friend for which Student Details is null, but this probably means we have friends in Friends Service for which we don't have suitable elements in Student Service.

**Comment by eggwhat** [comment]
Unfortunately there are many instances that are not synchronized across many services. I would recommend clearing the databases and see if these issues still occur.

**Comment by SaintAngeLs** [comment]
> Unfortunately there are many instances that are not synchronized across many services. I would recommend clearing the databases and see if these issues still occur.

I would agree with @eggwhat.

**Comment by SaintAngeLs** [comment]
@eggwhat, please drop the production database.

**Comment by eggwhat** [comment]
On my way

**Comment by eggwhat** [comment]
It should be empty now
