### ISSUE TITLE
The matter with organizations

### ISSUE THREAD

**Issue by DevITSharpPRO** [SaintAngeLs/distributed_minispace#303]
### Discussed in https://github.com/SaintAngeLs/distributed_minispace/discussions/302

<div type='discussions-op-text'>

<sup>Originally posted by **DevITSharpPRO** July 14, 2024</sup>
Dear developers,

Please provide us with the information about the matter with organization service: what is the purpose of the organisations service and the events service is there is not possible to create any organisation nor event as the authenticated user?

I would be grateful for this feature provisioning.
</div>

**Comment by SaintAngeLs** [comment]
Currently, this issue will be declared as closed with the status of duplication #298.
