### ISSUE TITLE
Ntrada update

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/distributed_minispace#31]
Ports for services:
- Identity - 5004
- Reports - 5005
- Notifications - 5006
- Students - 5007
- Events - 5008
- Comments - 5009
- Reactions - 5010
- Statistics - 5011
- Friends - 5012
- Posts - 5013
- MediaFiles - 5014
- Organizations - 5015
- Mailing - 5016

**Comment by an2508374** [comment]
In ntradaUpdate branch we have now a template for endpoints for almost all our microservices:
- Downstream endpoints should be consistent with the diagram: https://app.diagrams.net/#G1BsP1sv_9fAmCtE4uVDHizcFcp7TqqvXc#%7B%22pageId%22%3A%229VrkRtQQe1OaMDu59Q1v%22%7D
- Upstream endpoints now are generally based on downstream endpoints, in the future it will be necessary to adjust them to the general documentation for all teams (that one incomplete and not frozen yet)
- For some endpoints attributes "bind" and "claims" needs to be set in the suitable way, it was not taken into account by me, also please pay attention to the fact that "auth" is set as true in every place

**Comment by eggwhat** [comment]
- update .net to 8.0

**Comment by an2508374** [comment]
Ports for services:
- Identity - 5004
- Reports - 5005
- Notifications - 5006
- Students - 5007
- Events - 5008
- Comments - 5009
- Reactions - 5010
- Statistics - 5011
- Friends - 5012
- Posts - 5013
- MediaFiles - 5014
- Organizations - 5015
- Mailing - 5016

**Comment by SaintAngeLs** [comment]
At this moment of development this issue will become inactive.
