### ISSUE TITLE
[FEATURE][EVENTSBACK-2] Organizations service delivery

### ISSUE THREAD

**Issue by eggwhat** [SaintAngeLs/distributed_minispace#330]
# Organizational Features

### Create Organizations or Sub-organizations
- Users can create and manage main organizations and sub-organizations.
- Organizations can be private, visible/invisible on the organizations list.
- To access a private organization, users must send a request.
- Requests to join private organizations should be resolved by the group role with permissions for this action.
- Permissions may be assigned by the group creator and administrators.
- The group creator defines the permissions for the admins and, for instance, the second role of moderators.

### Assign Roles and Permissions
- Group creators are a separate role and cannot be assigned.
- Group administrators can be assigned and their permissions defined by the group creator.
- Group moderators can be assigned by the admin or creator with defined permissions.
- Group users, with each role having its permissions.

### Invite and Manage Members
- Invite users to organizations and sub-organizations.
- Manage members within the organization.

### Posts Creation in Group
- Specified user roles should be allowed to create posts.
- Posts may be created according to permissions granted.

### Event Coordination
- Specified user roles (moderators or other roles with permissions) can create and manage events, track participation, and gather feedback.
- A new user role, Event Organizer, can be suggested for the group or subgroup.

## Communication Tools
- Tools for internal communication and coordination among organization members.

### Organization's Feed List
- Posts, events, and comments related to the specific organization.
- This feed will also be connected to the users-participants' personal feed.
- If \( X_{i_i} \) is the sub-organization of \( X_i \) and \( X_{i_i} \) is not private and is public, then if the \( \text{Feed}(.) \) is the function generating the feed of '.', then \( \text{Feed}(X_i) \) contains \( \text{Feed}(X_{i_i}) \).

### Suggested Organization Roles-Permissions
- **Group Creator:** Cannot be assigned. Has the highest level of control over the organization and defines permissions for other roles.
- **Group Administrator:** Can be assigned by the group creator. Permissions are defined by the group creator.
- **Group Moderator:** Can be assigned by the group admin or creator. Permissions are defined by the assigning authority.
- **Event Organizer:** Suggested role for creating and managing events.
- **Group User:** Each role within this category will have specific permissions defined by the group creator or administrators.

### Organizational Management Permissions
- **May create sub-groups:** Allows the user to create sub-organizations within the main organization.
- **May delete sub-groups:** Allows the user to delete sub-organizations.
- **May edit organization details:** Allows the user to edit the details of the organization or sub-organization.

### Membership Management Permissions
- **May invite to the group:** Allows the user to invite other users to join the organization.
- **May remove members:** Allows the user to remove members from the organization or sub-organization.
- **May manage membership requests:** Allows the user to approve or reject membership requests for private organizations.

### Content Creation and Interaction Permissions
- **May make posts:** Allows the user to create posts within the organization or sub-organization.
- **May edit posts:** Allows the user to edit any post within the organization or sub-organization.
- **May delete posts:** Allows the user to delete any post within the organization or sub-organization.
- **May comment on posts:** Allows the user to comment on posts within the organization or sub-organization.
- **May delete comments:** Allows the user to delete any comment within the organization or sub-organization.
- **May make reactions:** Allows the user to react to posts and comments within the organization or sub-organization.
- **May pin posts:** Allows the user to pin important posts at the top of the organization's feed.

### Event Management Permissions
- **May create events:** Allows the user to create events within the organization or sub-organization.
- **May edit events:** Allows the user to edit any event within the organization or sub-organization.
- **May delete events:** Allows the user to delete any event within the organization or sub-organization.
- **May manage event participation:** Allows the user to track and manage event participation.

### Administrative Permissions
- **May assign roles:** Allows the user to assign roles to other members within the organization or sub-organization.
- **May edit permissions:** Allows the user to edit the permissions of roles within the organization or sub-organization.
- **May view audit logs:** Allows the user to view the history of changes and actions taken within the organization or sub-organization.

### Communication Permissions
- **May send messages to all members:** Allows the user to send messages to all members within the organization or sub-organization.
- **May create communication channels:** Allows the user to create specific communication channels or groups within the organization or sub-organization.

### Feed Management Permissions
- **May manage organization feed:** Allows the user to manage the organization's feed, including curating content and managing visibility of posts.
- **May moderate content:** Allows the user to moderate content, ensuring it adheres to the organization's guidelines and policies.

### Custom Permissions
- **Custom permissions:** Allows the creation of custom permissions specific to the needs of the organization or sub-organization. This could include permissions like "May access financial reports," "May manage external collaborations," etc.

Delivery feature will contain: 
 - updated optimised api
 - updated corresponding blazor application components
 - (possibly planned) updated notification service for organisation service updated feature
 - documentation readme update

**Comment by SaintAngeLs** [comment]
#341 resolves thie issue.
