### ISSUE TITLE
[BUG] Please check if the guid is not used in the database

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/distributed_minispace#331]
When creating the new object, please check if Guid was not previously used.

**Comment by eggwhat** [comment]
Does it make sense to check it everywhere except special cases? The chance for duplication is extremely low and when there is attempt to create an object with the same GUID the bad request will be returned.

**Comment by SaintAngeLs** [comment]
Thank you for reply. This issue was opened with the think of future in mind but still Guid May theoretically contain ~2^128 or ~3.4×10^38, so, theoretically, there is not a reasonable need to check it currently for current number of users. But there should be a point to be afraid of that the chance will be, that 2 users may get 1 Guid. In scaled systems is so important.
