### ISSUE TITLE
[FEATURE] Methods for abstract cropper

### ISSUE THREAD

**Issue by DevITSharpPRO** [SaintAngeLs/distributed_minispace#344]
#330 Showed, that you're currently using the same cropper model for both banner images and profile images in organisations. Is seems, that the better feature will be appliable for the different sort of images, the better for users experience. May you, please think in that direction and update the implementation of abstract cropper?

**Comment by SaintAngeLs** [comment]
@DevITSharpPRO Thank you for reference this  issue. We are currently working to implement the abstract cropper with theoretical boundaries for images and special cases for banner images.
