### ISSUE TITLE
Frontend development

### ISSUE THREAD

**Issue by an2508374** [SaintAngeLs/distributed_minispace#57]
New functions will be documented in branch called "frontend".

**Comment by eggwhat** [comment]
I added services for posts and events. How can I help you next?

**Comment by SaintAngeLs** [comment]
I will provide the frontend version of the app.

**Comment by an2508374** [comment]
> I added services for posts and events. How can I help you next?

I think you can try preparing some error handling connected with checking codes of http requests. We have it now only for signing in. In this moment it is done without checking codes, but it uses RadzenAlert component in which we can show error messages.

**Comment by eggwhat** [comment]
I provided a change to identity service. Hope this is what you wanted.

**Comment by SaintAngeLs** [comment]
@an2508374  @eggwhat  also there is a need to provide a blazor forms validation for the user input and the controller responses both.

**Comment by eggwhat** [comment]
> I provided a change to identity service. Hope this is what you wanted.

It created a bug when logging with invalid credentials. I will fix it on `frontend_error_handling` branch

**Comment by eggwhat** [comment]
I won't be changing identity service, because name and email in token is needed also for backend. So I suggest using identity/me to get userId

**Comment by SaintAngeLs** [comment]
#140 #125 are also the features regarding this feature.

**Comment by SaintAngeLs** [comment]
Still there is an update needed for the more responsive frontend.
