### ISSUE TITLE
Issue with the events service and frontend branch

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/distributed_minispace#71]
@an2508374  @SaintAngeLs @eggwhat  @olegkiprik  @zniwiarzxxx , I've merged responsive frontend version for future demonstration. Currently the problem is the next one: the frontend branch does not contain the Events service. I suggest that we should merge it with dev now, and after continue the work in the new branch (#57).

**Comment by SaintAngeLs** [comment]
Currently all the changes are in the dev branch (#72).

**Comment by eggwhat** [comment]
I created new branch `frontend_update`

**Comment by eggwhat** [comment]
This issue is closed due to inactivity
